apiVersion: v1
kind: Service
metadata:
  name: notify-push
  namespace: nextcloud
spec:
  selector:
    app: notify-push
  ports:
    - name: http
      port: 7867
      targetPort: 7867
  type: ClusterIP
