# Notify-push Horizontal Pod Autoscaler
# Ajusta automáticamente el número de réplicas del despliegue de Notify-push en función de la utilización de CPU.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notify-push-hpa
  namespace: nextcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notify-push
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Objetivo de utilización de CPU del 60%
