apiVersion: v1
kind: Service
metadata:
  name: turn-rest-api-service
  namespace: talk
  labels:
    app: turn-rest-api
spec:
  selector:
    app: turn-rest-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
